### ISSUE TITLE
for the gitRepo can we support both public key and private key

### ISSUE THREAD

**Issue by nimakaviani** [nimakaviani/managed-delivery-k8s-plugin#36]
If we want the repo to be accessible via SSH and using flux, we need to satisfy the following secret spec. Note the part on `SSH credentials`.

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: my-repository-creds
  namespace: default
data:
  # HTTP/S basic auth credentials
  username: <base64 encoded username>
  password: <base64 encoded password>
  # SSH credentials
  identity: <base64 encoded private key>
  identity.pub: <base64 public key>
  known_hosts: <base64 encoded known_hosts>
```
