### ISSUE TITLE
Wrong image could be picked as the artifact if clouddriver does not properly filter the list of returned images

### ISSUE THREAD

**Issue by nimakaviani** [nimakaviani/managed-delivery-k8s-plugin#62]
When clouddriver returns a list of images from a `findDockerImages` call, the plugin picks the first image as the expected artifact on L58 here:

https://github.com/nimakaviani/managed-delivery-k8s-plugin/blob/4a782bb20f96648f42aa1ef64455a135fe3a290f/k8s-plugin/src/main/kotlin/com/amazon/spinnaker/keel/k8s/resolver/DockerImageResolver.kt#L56-L59

For this to work correctly, either clouddriver needs to respect the filtering passed to its `/find` endpoint to only return the image from the correct repository, or it has to be configured to work against expected repositories like below (note the reference to `example/service`):

```
dockerRegistry:
accounts:
- address: https://index.docker.io # example registry
  name: "[K8s-ACCOUNT-NAME]-registry"
  repositories:
  - example/service
```  

Regardless, the plugin once receiving the list of images back from clouddriver, needs to verify that the first image it receives, indeed matches the image it expects. if not, it should set the artifact reference to `null` and log an error message.
