### ISSUE TITLE
issues using private docker registry

### ISSUE THREAD

**Issue by JonGilmore** [nimakaviani/managed-delivery-k8s-plugin#63]
Hello! We are using Jfrog Artifactory for our docker registry (we use their virtual repos to mirror dockerhub and local repos to simplify resolution), and I think I've come across an issue with this. We have the plugin up and working, but the pod will never actually start, it throws the following error: 
```
Failed to pull image "releng/nginx:1.0.8": rpc error: code = Unknown desc = Error response from daemon: pull access denied for releng/nginx, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```
When I go to the k8s cluster itself to check on the pod, it shows that the deployment has the following config:

![Screen Shot 2021-06-23 at 2 48 47 PM](https://user-images.githubusercontent.com/7232986/123280993-e8432c80-d4ce-11eb-84a9-6d0d260955fd.png)

As you can see from the above, you'll notice that the container image is `releng/nginx:1.0.8` - k8s will attempt to go out to dockerhub to grab this image and fail because it doesn't exist there. What we really need (I think?) this plugin to do is to fill in the image as follows:
```
containers:
  - image: myorg.jfrog.io/releng/nginx:1.0.8
```

I _think_ this is loosely related to [this conversation](https://spinnakerteam.slack.com/archives/CERACDPDZ/p1623781782094000?thread_ts=1623775571.082800&cid=CERACDPDZ) where we were discussing the usage of multiple slashes in the artifact name, but I'm not entirely sure. Our MD manifest artifact looks like this:
```
name: keeldemo
application: keeldemo
artifacts:
  - name: releng/nginx
    type: docker
    reference: releng/nginx
    tagVersionStrategy: semver-tag
```
on clouddriver, our docker config looks as follows:
```
dockerRegistry:
  enabled: true
  accounts:
    - name: sandbox-us-east-1-registry
      address: https://myorg.jfrog.io
      username: clouddriver-sb
      password: ${artifactory-token}
      repositories:
        - releng/nginx
```
To be very honest, I'm not sure if this is a misconfiguration in my manifest, or a bug in keel/clouddriver/keel k8s plugin or what, but I figured a github issue might be the best place to start :D

Let me know if you need additional details, thanks!!
