### ISSUE TITLE
resolve artifact reference in k8s resource

### ISSUE THREAD

**Issue by nimakaviani** [nimakaviani/managed-delivery-k8s-plugin#8]
One should be able to define artifacts for Kubernetes resources in the delivery manifest of spinnaker and have the delivery manifest reference them. Also, the lifecycle of these artifacts should be managed through the mechanism already available in managed delivery.

An example would be like the following:

```yaml
name: my-k8s-manifest
application: eks-k8s
serviceAccount: sekret-service-account@spinnaker-test.net
artifacts:
- name: nimak/helloworld
  type: docker
  reference: my-docker-artifact
  tagVersionStrategy: semver-tag
environments:
  - name: testing
    locations:
      account: my-k8s-account
      regions: []
    resources:
    - kind: k8s/resource@v1
     container:
       reference: my-docker-artifact
      spec:
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: yollo-testing
          namespace: default
        spec:
          replicas: 2
          selector:
            matchLabels:
              app: hello
          template:
            metadata:
              labels:
                app: hello
            spec:
              containers:
              - name: hello
                image: my-docker-artifact
                ports:
                - containerPort: 8080
```

The reference name under `container.reference` and the `spec.containers[].image` is what binds an artifact to the given resource.
