### ISSUE TITLE
Null value for artifactSpec causes failures in loading the MD environment

### ISSUE THREAD

**Issue by nimakaviani** [nimakaviani/managed-delivery-k8s-plugin#82]
with a helm resource like the following:

```yaml
   - kind: k8s/helm@v1
      spec:
        metadata:
          application: spinmd
        template:
          metadata:
            namespace: default
            name: my-release
          spec:
            interval: 10m
            values:
              image:
                repository: nimak/helloworld
                tag: 1.7
            chart:
              spec:
                chart: ./chart/hello
                sourceRef:
                  kind: GitRepository
                  name: my-repository
                  namespace: default
```

I am getting the following error message after updating to the latest version of the plugin and my managed delivery environment fails to load.

```java
com.fasterxml.jackson.module.kotlin.MissingKotlinParameterException: Instantiation of [simple type, class com.amazon.spinnaker.keel.k8s.model.HelmResourceSpec] value failed for JSON property artifactSpec due to missing (therefore NULL) va
lue for creator parameter artifactSpec which is a non-nullable type
 at [Source: (String)"{"id": "my-k8s-west-account-default-helmrelease-my-release", "metadata": {"application": "spinmd"}, "template": {"kind": "HelmRelease", "spec": {"chart": {"spec": {"chart": "./chart/hello", "sourceRef": {"kind": "Git
Repository", "name": "my-repository", "namespace": "default"}}}, "values": {"image": {"tag": 1.7, "repository": "nimak/helloworld"}}, "interval": "10m"}, "metadata": {"name": "my-release", "namespace": "default"}, "apiVersion": "helm.tool
kit.fluxcd.io/v2beta1"}, "locations": {"vpc": "[truncated 106 chars]; line: 1, column: 606] (through reference chain: com.amazon.spinnaker.keel.k8s.model.HelmResourceSpec["artifactSpec"])
        at com.fasterxml.jackson.module.kotlin.KotlinValueInstantiator.createFromObjectWith(KotlinValueInstantiator.kt:112) ~[jackson-module-kotlin-2.11.1.jar:2.11.1]
        at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:202) ~[jackson-databind-2.12.3.jar:2.12.3]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:520) ~[jackson-databind-2.12.3.jar:2.12.3]
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1405) ~[jackson-databind-2.12.3.jar:2.12.3]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:362) ~[jackson-databind-2.12.3.jar:2.12.3]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:195) ~[jackson-databind-2.12.3.jar:2.12.3]
        at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322) ~[jackson-databind-2.12.3.jar:2.12.3]
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4593) ~[jackson-databind-2.12.3.jar:2.12.3]
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3548) ~[jackson-databind-2.12.3.jar:2.12.3]
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3516) ~[jackson-databind-2.12.3.jar:2.12.3]
        at com.netflix.spinnaker.keel.sql.ResourceFactory.invoke(ResourceFactory.kt:30) ~[keel-sql.jar:na]
        at com.netflix.spinnaker.keel.sql.deliveryconfigs.DeliveryconfigsKt$resourcesForEnvironment$1$1.map(deliveryconfigs.kt:164) ~[keel-sql.jar:na]
        at com.netflix.spinnaker.keel.sql.deliveryconfigs.DeliveryconfigsKt$resourcesForEnvironment$1$1.map(deliveryconfigs.kt) ~[keel-sql.jar:na]
        at org.jooq.impl.ResultImpl.map(ResultImpl.java:1317) ~[jooq-3.13.2.jar:na]
        at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:1565) ~[jooq-3.13.2.jar:na]
        at org.jooq.impl.SelectImpl.fetch(SelectImpl.java:3761) ~[jooq-3.13.2.jar:na]
        at com.netflix.spinnaker.keel.sql.deliveryconfigs.DeliveryconfigsKt$resourcesForEnvironment$1.invoke(deliveryconfigs.kt:163) ~[keel-sql.jar:na]
        at com.netflix.spinnaker.keel.sql.deliveryconfigs.DeliveryconfigsKt$resourcesForEnvironment$1.invoke(deliveryconfigs.kt) ~[keel-sql.jar:na]
        at com.netflix.spinnaker.keel.sql.SqlRetry$sam$java_util_function_Supplier$0.get(SqlRetry.kt) ~[keel-sql.jar:na]
        at io.github.resilience4j.retry.Retry.lambda$decorateSupplier$2(Retry.java:213) ~[resilience4j-retry-1.5.0.jar:1.5.0]
        at io.vavr.control.Try.of(Try.java:75) ~[vavr-0.10.2.jar:na]```
